### ISSUE TITLE
Change color when tests not passing

### ISSUE THREAD

**Issue by aj07mm** [gustavoFreireS/electron-dojo-timer#11]

**Comment by gustavoFreireS** [comment]
depends on #12  to be executed

**Comment by gustavoFreireS** [comment]
the ideal approach would be using the [child_process](https://nodejs.org/api/child_process.html) built in Api for node.js and execute a system command direct from the browser, if it succeds it will print the output on `stdout` parameter if not, on `stderr` parameter

**Comment by gustavoFreireS** [comment]
solved on #12
